version: "3"

services:
  mongodb:
    container_name: mongodb
    image: "mongo:7.0.7"
    ports: 
      - "27017:27017"
    networks:
      - my-network
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_URL: mongodb://mongodb:27017/pets
      PORT: 3000

networks:
  my-network:
    driver: bridge
